name: evidyalaya
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  connectivity_plus: ^3.0.2
  flutter_spinkit: ^5.1.0
  mysql1: ^0.20.0
  crypto: ^3.0.2
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.7
  firebase_core: ^2.4.0
  cloud_firestore: ^4.3.0
  mailer: ^5.3.0
  file_picker: ^5.2.5
  firebase_storage: ^11.0.10
  image_picker: ^0.8.6+1
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/